(byte-recompile-directory (concat user-emacs-directory "core"))
(dolist (f '("params" "key" "pkgs"))
  (byte-recompile-file (concat user-emacs-directory f)))
(loaddefs-generate (concat user-emacs-directory "core")
                   (concat user-emacs-directory "core/core-autoloads.el"))
